Create Base API
awesome-academy/HN_Pra19_Android_Finance_App pull request #4
Opened 2024-07-27 12:22 UTC by xuanthu2002

## Related Tickets
- [#Task 78533: Create Base API](https://edu-redmine.sun-asterisk.vn/issues/78533)
## WHAT
- Create Base API
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-07-27 12:50 UTC, MaxHolmes221B approved these changes

2024-07-29 02:09 UTC, TranTinh030892 approved these changes

2024-07-30 02:12 UTC, gianghv-3456 requested changes
check my cmts

2024-07-30 02:12 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/data/model/Coin.kt
> +    }
Tách các model thành các file riêng em ạ, không ôm đồm thế này, enum thì nên move sang 1 chỗ riêng (constant)

2024-07-30 02:12 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/data/repository/source/CoinDataSource.kt
> +        fun getLocalCoins(listener: OnResultListener<MutableList<Coin>>)
Dùng List thay vì MutableList em ơi, Data từ tầng Source trả về là cố định mà
```suggestion
        fun getLocalCoins(listener: OnResultListener<List<Coin>>)
```

2024-07-30 02:12 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/data/repository/source/CoinDataSource.kt
> +            offset: Int = 0,
Nhiều tham số quá, sao em pass được detekt vậy???
Em có thể gom các param liên quan vào các class. Ví dụ: OrderProperties chứa cả OrderBy và OrderDirection, limit, offset, ....

2024-07-30 02:12 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/data/repository/source/remote/CoinRemoteDataSource.kt
> +        offset: Int,
Nhiều tham số quá e

2024-08-01 03:01 UTC, gianghv-3456 approved these changes

2024-08-01 04:00 UTC, merged