Create UI - Coin Detail
awesome-academy/HN_Pra19_Android_Finance_App pull request #6
Opened 2024-08-05 06:41 UTC by TranTinh030892

## Related Tickets
- [#Task 78291: Content](https://edu-redmine.sun-asterisk.vn/issues/78291)
## WHAT
- Create UI - Coin Detail
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-08-05 07:03 UTC, xuanthu2002 approved these changes

2024-08-05 07:20 UTC, MaxHolmes221B approved these changes

2024-08-06 03:57 UTC, HVgiang86 requested changes
check cmt

2024-08-06 03:57 UTC, HVgiang86 commented on app/src/main/res/anim/slide_out_right.xml
> +</set>
End of file
```suggestion
</set>

```

2024-08-06 04:18 UTC, gianghv-3456 requested changes
.

2024-08-06 05:18 UTC, gianghv-3456 approved these changes

2024-08-06 05:18 UTC, merged