Handle Event - Coin Detail
awesome-academy/HN_Pra19_Android_Finance_App pull request #7
Opened 2024-08-06 08:41 UTC by TranTinh030892

## Related Tickets
- [#Task 79252: Handle Event - Coin Detail](https://edu-redmine.sun-asterisk.vn/issues/79252)
## WHAT
- Handle Event - Coin Detail
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-08-06 08:43 UTC, xuanthu2002 commented on app/src/main/java/com/example/fina/screen/detail/ChartExt.kt
> +    leftAxis.gridColor = Color.parseColor("#FFDBDDE8")
Hard code.

2024-08-06 15:22 UTC, MaxHolmes221B approved these changes

2024-08-07 04:32 UTC, xuanthu2002 approved these changes

2024-08-07 06:18 UTC, gianghv-3456 requested changes
.

2024-08-07 06:18 UTC, gianghv-3456 commented on app/build.gradle
Bỏ change file này

2024-08-07 06:18 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/utils/ext/ViewExt.kt
> +        delay(delayMillis)
Project 1 không sử dụng Coroutine em nhé

2024-08-07 07:39 UTC, gianghv-3456 requested changes

2024-08-07 07:39 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/screen/detail/DetailPresenter.kt
> +            TODO()
```suggestion
            /* no-op */
```

2024-08-07 07:39 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/screen/detail/DetailPresenter.kt
> +            TODO()
```suggestion
            
```

2024-08-07 07:39 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/screen/detail/DetailPresenter.kt
> +class DetailPresenter internal constructor(private val coinRepository: CoinRepository?) :
Repository không được phép null em
```suggestion
class DetailPresenter internal constructor(private val coinRepository: CoinRepository) :
```

2024-08-07 07:39 UTC, gianghv-3456 commented on app/src/main/java/com/example/fina/screen/detail/ChartExt.kt
> +        val pixelPos = FloatArray(2)
Code rối quá, format lại tí e

2024-08-07 08:14 UTC, gianghv-3456 approved these changes

2024-08-07 08:14 UTC, merged